-- ============================================================
-- 语义层全面更新脚本
-- 基于真实表结构 (ddl.sql) 和 441条测试数据集
-- 执行前请备份现有数据
-- ============================================================

USE text02_semantic;

-- ============================================================
-- 步骤1：补充标准指标维度字典表
-- ============================================================

-- 店铺域 - 补充 store_ratings 评分相关指标和维度
INSERT INTO `standard_metrics_dimensions` (`name`, `type`, `physical_table`, `physical_field`, `field_type`, `business_desc`, `aggregation_type`, `domain`) VALUES
-- 评分相关指标
('评价数量', 'metric', 'store_ratings', 'rating_id', 'BIGINT', '评价总次数', 'COUNT', '店铺域'),
('平均描述相符评分', 'metric', 'store_ratings', 'description_score', 'DECIMAL(2,1)', '店铺描述相符平均分', 'AVG', '店铺域'),
('平均服务态度评分', 'metric', 'store_ratings', 'service_score', 'DECIMAL(2,1)', '服务态度平均分', 'AVG', '店铺域'),
('平均物流服务评分', 'metric', 'store_ratings', 'logistics_score', 'DECIMAL(2,1)', '物流服务平均分', 'AVG', '店铺域'),
('平均综合评分', 'metric', 'store_ratings', 'description_score', 'DECIMAL(2,1)', '三项评分平均值', 'AVG', '店铺域'),
-- 评分相关维度
('是否有图评价', 'dimension', 'store_ratings', 'has_image', 'TINYINT', '是否有图：0=否 1=是', NULL, '店铺域'),
('评价时间', 'dimension', 'store_ratings', 'rating_time', 'DATETIME', '评价时间', NULL, '店铺域'),
-- 订单相关指标补充
('订单数量', 'metric', 'orders', 'order_id', 'BIGINT', '订单总数', 'COUNT', '交易域'),
('订单总金额', 'metric', 'orders', 'total_amount', 'DECIMAL(12,2)', '订单总金额(GMV)', 'SUM', '交易域'),
('实付金额', 'metric', 'orders', 'pay_amount', 'DECIMAL(12,2)', '实际支付金额', 'SUM', '交易域'),
('优惠金额', 'metric', 'orders', 'discount_amount', 'DECIMAL(12,2)', '优惠减免金额', 'SUM', '交易域'),
('客单价', 'metric', 'orders', 'pay_amount', 'DECIMAL(12,2)', '人均消费金额', 'AVG', '交易域'),
-- 订单明细相关指标
('商品购买数量', 'metric', 'order_items', 'quantity', 'INT', '购买商品数量', 'SUM', '交易域'),
('退款商品数量', 'metric', 'order_items', 'quantity', 'INT', '退款商品数量', 'SUM', '交易域'),
-- 优惠券相关指标
('优惠券发放数量', 'metric', 'coupons', 'total_count', 'INT', '优惠券发放总数', 'SUM', '营销域'),
('优惠券领取数量', 'metric', 'user_coupons', 'id', 'BIGINT', '用户领券记录数', 'COUNT', '营销域'),
('优惠券已使用数量', 'metric', 'user_coupons', 'id', 'BIGINT', '已使用优惠券数', 'COUNT', '营销域'),
('优惠券未使用数量', 'metric', 'user_coupons', 'id', 'BIGINT', '未使用优惠券数', 'COUNT', '营销域'),
('优惠券核销率', 'metric', 'user_coupons', 'status', 'ENUM', '已核销/已领取', NULL, '营销域'),
-- 用户优惠券相关维度
('优惠券状态', 'dimension', 'user_coupons', 'status', 'ENUM', '领券状态(unused/used/expired)', NULL, '营销域'),
('领券时间', 'dimension', 'user_coupons', 'receive_time', 'DATETIME', '领取优惠券时间', NULL, '营销域'),
('用券时间', 'dimension', 'user_coupons', 'use_time', 'DATETIME', '使用优惠券时间', NULL, '营销域'),
('优惠券过期时间', 'dimension', 'user_coupons', 'expire_time', 'DATETIME', '优惠券过期时间', NULL, '营销域'),
-- 活动相关指标
('活动数量', 'metric', 'campaigns', 'campaign_id', 'BIGINT', '营销活动总数', 'COUNT', '营销域'),
('活动预算', 'metric', 'campaigns', 'budget', 'DECIMAL(12,2)', '活动预算总额', 'SUM', '营销域'),
('活动实际GMV', 'metric', 'campaigns', 'actual_gmv', 'DECIMAL(12,2)', '活动实际成交额', 'SUM', '营销域'),
('活动花费', 'metric', 'campaigns', 'cost', 'DECIMAL(12,2)', '活动已花费金额', 'SUM', '营销域'),
('活动下单数量', 'metric', 'campaigns', 'order_count', 'INT', '活动关联下单数', 'SUM', '营销域'),
('活动访问次数', 'metric', 'campaigns', 'visit_count', 'INT', '活动访问量', 'SUM', '营销域'),
-- 活动相关维度
('活动类型', 'dimension', 'campaigns', 'campaign_type', 'ENUM', '活动类型(flash_sale/group_buy/full_reduction/gift/lottery)', NULL, '营销域'),
('活动状态', 'dimension', 'campaigns', 'status', 'ENUM', '活动状态(planned/active/ended/cancelled)', NULL, '营销域'),
('是否平台级活动', 'dimension', 'campaigns', 'store_id', 'BIGINT', '平台级活动判断(store_id为NULL)', NULL, '营销域'),
-- 支付相关指标
('支付金额', 'metric', 'payments', 'amount', 'DECIMAL(12,2)', '支付金额合计', 'SUM', '交易域'),
('支付笔数', 'metric', 'payments', 'payment_id', 'BIGINT', '支付记录数', 'COUNT', '交易域'),
-- 物流相关指标
('物流单数量', 'metric', 'shipments', 'shipment_id', 'BIGINT', '物流单总数', 'COUNT', '物流域'),
('物流运费', 'metric', 'shipments', 'shipping_fee', 'DECIMAL(10,2)', '物流运费合计', 'SUM', '物流域'),
('平均物流运费', 'metric', 'shipments', 'shipping_fee', 'DECIMAL(10,2)', '平均每单运费', 'AVG', '物流域'),
-- 商品规格相关维度
('规格名称', 'dimension', 'product_specs', 'spec_name', 'VARCHAR', '规格名称（如颜色、尺码）', NULL, '商品域'),
('规格值', 'dimension', 'product_specs', 'spec_value', 'VARCHAR', '规格具体值', NULL, '商品域'),
('SKU编码', 'dimension', 'product_specs', 'sku_code', 'VARCHAR', 'SKU唯一编码', NULL, '商品域')
ON DUPLICATE KEY UPDATE `updated_at` = NOW(), `business_desc` = VALUES(`business_desc`);


-- ============================================================
-- 步骤2：补充口语别名映射表
-- 基于441条测试问句中的口语表达
-- ============================================================

INSERT INTO `spoken_aliases` (`spoken_term`, `standard_name`, `alias_type`, `frequency`, `source`) VALUES

-- ========== 评价相关 ==========
('有图评价', '是否有图评价', 'field', 50, 'dataset'),
('有图评价占比', '是否有图评价', 'field', 45, 'dataset'),
('没图评价', '是否有图评价', 'field', 45, 'dataset'),
('无图评价', '是否有图评价', 'field', 40, 'dataset'),
('带图评价', '是否有图评价', 'field', 35, 'dataset'),
('晒图评价', '是否有图评价', 'field', 30, 'dataset'),
('评价差异', '平均综合评分', 'field', 40, 'dataset'),
('评分差异', '平均综合评分', 'field', 45, 'dataset'),
('好评率', '平均描述相符评分', 'field', 60, 'dataset'),
('差评率', '平均描述相符评分', 'field', 50, 'dataset'),
('DSR评分', '平均综合评分', 'field', 55, 'dataset'),
('动态评分', '平均综合评分', 'field', 50, 'dataset'),
('店铺评分', '平均综合评分', 'field', 65, 'dataset'),
('商家评分', '平均综合评分', 'field', 60, 'dataset'),
('描述相符', '平均描述相符评分', 'field', 55, 'dataset'),
('服务态度', '平均服务态度评分', 'field', 50, 'dataset'),
('物流服务', '平均物流服务评分', 'field', 50, 'dataset'),
('评价内容', '评价数量', 'field', 40, 'dataset'),
('评价数', '评价数量', 'field', 60, 'dataset'),
('评价条数', '评价数量', 'field', 55, 'dataset'),
('评价总数', '评价数量', 'field', 50, 'dataset'),
('几条评价', '评价数量', 'field', 35, 'dataset'),
('几条', '评价数量', 'field', 30, 'dataset'),

-- ========== 优惠券相关 ==========
('优惠券', '优惠券发放数量', 'entity', 80, 'dataset'),
('券', '优惠券发放数量', 'entity', 75, 'dataset'),
('折扣券', '优惠券发放数量', 'entity', 65, 'dataset'),
('满减券', '优惠券发放数量', 'entity', 60, 'dataset'),
('代金券', '优惠券发放数量', 'entity', 55, 'dataset'),
('未使用的优惠券', '优惠券未使用数量', 'entity', 70, 'dataset'),
('尚未使用的优惠券', '优惠券未使用数量', 'entity', 65, 'dataset'),
('还没用的优惠券', '优惠券未使用数量', 'entity', 60, 'dataset'),
('未使用', '优惠券状态', 'value', 75, 'dataset'),
('未使用优惠券', '优惠券状态', 'entity', 70, 'dataset'),
('已使用的优惠券', '优惠券已使用数量', 'entity', 65, 'dataset'),
('已核销', '优惠券状态', 'value', 60, 'dataset'),
('已过期', '优惠券状态', 'value', 65, 'dataset'),
('过期', '优惠券状态', 'value', 60, 'dataset'),
('优惠券使用率', '优惠券核销率', 'field', 55, 'dataset'),
('券使用率', '优惠券核销率', 'field', 50, 'dataset'),
('核销率', '优惠券核销率', 'field', 65, 'dataset'),
('领取数量', '优惠券领取数量', 'field', 60, 'dataset'),
('领券数量', '优惠券领取数量', 'field', 55, 'dataset'),
('有几张', '优惠券发放数量', 'field', 45, 'dataset'),
('有多少张', '优惠券发放数量', 'field', 50, 'dataset'),
('有几张券', '优惠券发放数量', 'field', 45, 'dataset'),
('优惠券余额', '优惠券未使用数量', 'field', 50, 'dataset'),
('剩余券', '优惠券未使用数量', 'field', 55, 'dataset'),
('还有多少', '优惠券未使用数量', 'field', 50, 'dataset'),
('还剩多少', '优惠券未使用数量', 'field', 50, 'dataset'),
('使用优惠券', '优惠券已使用数量', 'field', 55, 'dataset'),
('用券', '优惠券已使用数量', 'field', 60, 'dataset'),
('用了几张', '优惠券已使用数量', 'field', 45, 'dataset'),
('打折券', '优惠券发放数量', 'entity', 50, 'dataset'),
('免邮券', '优惠券发放数量', 'entity', 45, 'dataset'),
('免运费的券', '优惠券发放数量', 'entity', 40, 'dataset'),
('即将过期', '优惠券过期时间', 'field', 55, 'dataset'),
('快过期', '优惠券过期时间', 'field', 50, 'dataset'),
('7天内过期', '优惠券过期时间', 'field', 45, 'dataset'),

-- ========== 活动相关 ==========
('活动', '活动数量', 'entity', 80, 'dataset'),
('促销活动', '活动数量', 'entity', 70, 'dataset'),
('营销活动', '活动数量', 'entity', 65, 'dataset'),
('平台级', '是否平台级活动', 'field', 75, 'dataset'),
('平台级活动', '是否平台级活动', 'entity', 80, 'dataset'),
('全平台活动', '是否平台级活动', 'entity', 75, 'dataset'),
('平台活动', '是否平台级活动', 'entity', 70, 'dataset'),
('全平台的', '是否平台级活动', 'field', 65, 'dataset'),
('活动有哪些', '活动数量', 'field', 60, 'dataset'),
('有哪些活动', '活动数量', 'field', 65, 'dataset'),
('进行中', '活动状态', 'value', 70, 'dataset'),
('正在进行', '活动状态', 'value', 65, 'dataset'),
('正在进行中', '活动状态', 'value', 60, 'dataset'),
('已结束', '活动状态', 'value', 65, 'dataset'),
('已取消', '活动状态', 'value', 60, 'dataset'),
('取消了', '活动状态', 'value', 55, 'dataset'),
('限时抢购', '活动类型', 'value', 60, 'dataset'),
('秒杀', '活动类型', 'value', 65, 'dataset'),
('团购', '活动类型', 'value', 60, 'dataset'),
('拼团', '活动类型', 'value', 55, 'dataset'),
('满减', '活动类型', 'value', 65, 'dataset'),
('满减活动', '活动类型', 'value', 60, 'dataset'),
('赠品', '活动类型', 'value', 50, 'dataset'),
('抽奖', '活动类型', 'value', 55, 'dataset'),
('ROI', '活动实际GMV', 'field', 70, 'dataset'),
('投入产出比', '活动实际GMV', 'field', 65, 'dataset'),
('投资回报率', '活动实际GMV', 'field', 60, 'dataset'),
('GMV', '活动实际GMV', 'field', 75, 'dataset'),
('成交额', '活动实际GMV', 'field', 70, 'dataset'),
('销售额', '活动实际GMV', 'field', 65, 'dataset'),
('目标完成率', '活动实际GMV', 'field', 60, 'dataset'),
('活动预算', '活动预算', 'field', 55, 'dataset'),
('活动花费', '活动花费', 'field', 50, 'dataset'),
('成本', '活动花费', 'field', 55, 'dataset'),
('有几场', '活动数量', 'field', 45, 'dataset'),
('有几场活动', '活动数量', 'field', 50, 'dataset'),
('举办', '活动数量', 'field', 55, 'dataset'),
('举办了', '活动数量', 'field', 50, 'dataset'),
('办了多少', '活动数量', 'field', 45, 'dataset'),

-- ========== 订单状态相关 ==========
('待付款', '订单状态', 'value', 80, 'dataset'),
('待支付', '订单状态', 'value', 75, 'dataset'),
('未付款', '订单状态', 'value', 70, 'dataset'),
('还没付', '订单状态', 'value', 65, 'dataset'),
('未支付', '订单状态', 'value', 60, 'dataset'),
('已付款', '订单状态', 'value', 75, 'dataset'),
('已支付', '订单状态', 'value', 70, 'dataset'),
('已发货', '订单状态', 'value', 75, 'dataset'),
('发货了', '订单状态', 'value', 70, 'dataset'),
('待发货', '订单状态', 'value', 65, 'dataset'),
('已收货', '订单状态', 'value', 80, 'dataset'),
('收到货', '订单状态', 'value', 75, 'dataset'),
('收到了', '订单状态', 'value', 70, 'dataset'),
('签收了', '订单状态', 'value', 65, 'dataset'),
('已签收', '订单状态', 'value', 70, 'dataset'),
('运输中', '物流状态', 'value', 70, 'dataset'),
('在途中', '物流状态', 'value', 60, 'dataset'),
('快递在跑', '物流状态', 'value', 55, 'dataset'),
('已取消', '订单状态', 'value', 70, 'dataset'),
('已退款', '订单状态', 'value', 65, 'dataset'),
('退款中', '订单状态', 'value', 60, 'dataset'),
('退款', '退款商品数量', 'field', 65, 'dataset'),
('退过款', '退款商品数量', 'field', 55, 'dataset'),

-- ========== 支付相关 ==========
('微信支付', '支付金额', 'field', 70, 'dataset'),
('微信付款', '支付金额', 'field', 65, 'dataset'),
('用微信', '支付金额', 'field', 60, 'dataset'),
('支付宝', '支付金额', 'field', 70, 'dataset'),
('银行卡', '支付金额', 'field', 65, 'dataset'),
('分期', '支付金额', 'field', 55, 'dataset'),
('分期付款', '支付金额', 'field', 60, 'dataset'),
('余额支付', '支付金额', 'field', 50, 'dataset'),
('支付成功', '支付金额', 'field', 65, 'dataset'),
('付款成功', '支付金额', 'field', 60, 'dataset'),
('支付失败', '支付金额', 'field', 55, 'dataset'),
('流水', '支付笔数', 'field', 60, 'dataset'),
('支付流水', '支付笔数', 'field', 55, 'dataset'),
('交易笔数', '支付笔数', 'field', 65, 'dataset'),
('交易数量', '支付笔数', 'field', 70, 'dataset'),
('交易金额', '支付金额', 'field', 75, 'dataset'),

-- ========== 物流相关 ==========
('顺丰', '物流单数量', 'field', 70, 'dataset'),
('顺丰速运', '物流单数量', 'field', 65, 'dataset'),
('圆通', '物流单数量', 'field', 60, 'dataset'),
('中通', '物流单数量', 'field', 55, 'dataset'),
('韵达', '物流单数量', 'field', 55, 'dataset'),
('申通', '物流单数量', 'field', 55, 'dataset'),
('EMS', '物流单数量', 'field', 50, 'dataset'),
('京东物流', '物流单数量', 'field', 60, 'dataset'),
('快递公司', '物流单数量', 'field', 65, 'dataset'),
('哪个快递', '物流单数量', 'field', 50, 'dataset'),
('哪家', '物流单数量', 'field', 45, 'dataset'),
('签收率', '物流单数量', 'field', 65, 'dataset'),
('妥投率', '物流单数量', 'field', 55, 'dataset'),
('送达时间', '平均物流运费', 'field', 50, 'dataset'),
('耗时', '平均物流运费', 'field', 55, 'dataset'),
('物流耗时', '平均物流运费', 'field', 60, 'dataset'),
('平均耗时', '平均物流运费', 'field', 55, 'dataset'),
('发货时间', '物流单数量', 'field', 50, 'dataset'),
('签收时间', '物流单数量', 'field', 50, 'dataset'),
('物流状态', '物流单数量', 'field', 60, 'dataset'),
('包裹', '物流单数量', 'field', 70, 'dataset'),
('快递', '物流单数量', 'field', 75, 'dataset'),
('运单', '物流单数量', 'field', 60, 'dataset'),
('运单号', '物流单数量', 'field', 55, 'dataset'),
('快递单号', '物流单数量', 'field', 50, 'dataset'),

-- ========== 店铺类型相关 ==========
('旗舰店', '店铺类型', 'value', 70, 'dataset'),
('专营店', '店铺类型', 'value', 60, 'dataset'),
('加盟店', '店铺类型', 'value', 55, 'dataset'),
('个人店', '店铺类型', 'value', 50, 'dataset'),
('营业中', '店铺状态', 'value', 70, 'dataset'),
('营业', '店铺状态', 'value', 75, 'dataset'),
('关闭', '店铺状态', 'value', 65, 'dataset'),
('已关闭', '店铺状态', 'value', 60, 'dataset'),
('冻结', '店铺状态', 'value', 55, 'dataset'),
('审核中', '店铺状态', 'value', 50, 'dataset'),

-- ========== 商品相关 ==========
('商品', '商品购买数量', 'entity', 80, 'dataset'),
('货品', '商品购买数量', 'entity', 75, 'dataset'),
('物品', '商品购买数量', 'entity', 60, 'dataset'),
('商品数量', '商品购买数量', 'field', 70, 'dataset'),
('有多少个', '商品购买数量', 'field', 55, 'dataset'),
('有几个', '商品购买数量', 'field', 50, 'dataset'),
('上架', '商品状态', 'value', 70, 'dataset'),
('下架', '商品状态', 'value', 65, 'dataset'),
('预售', '商品状态', 'value', 60, 'dataset'),
('品牌名', '商品状态', 'field', 55, 'dataset'),
('牌子', '商品状态', 'field', 50, 'dataset'),
('价格区间', '平均价格', 'field', 60, 'dataset'),
('销量最高', '商品购买数量', 'field', 70, 'dataset'),
('最热门', '商品购买数量', 'field', 65, 'dataset'),
('热销', '商品购买数量', 'field', 70, 'dataset'),
('爆款', '商品购买数量', 'field', 60, 'dataset'),
('颜色', '规格名称', 'value', 65, 'dataset'),
('尺码', '规格名称', 'value', 60, 'dataset'),
('内存', '规格名称', 'value', 55, 'dataset'),
('黑色', '规格值', 'value', 50, 'dataset'),
('库存', '商品状态', 'field', 60, 'dataset'),
('标签', '商品状态', 'field', 55, 'dataset'),

-- ========== 用户相关 ==========
('买家', '用户数量', 'entity', 75, 'dataset'),
('会员', '用户数量', 'entity', 70, 'dataset'),
('顾客', '用户数量', 'entity', 65, 'dataset'),
('买家数', '用户数量', 'field', 60, 'dataset'),
('买家数量', '用户数量', 'field', 55, 'dataset'),
('客户', '用户数量', 'entity', 70, 'dataset'),
('消费金额', '支付金额', 'field', 75, 'dataset'),
('消费总额', '支付金额', 'field', 70, 'dataset'),
('总消费', '支付金额', 'field', 65, 'dataset'),
('消费排名', '支付金额', 'field', 70, 'dataset'),
('购买', '支付金额', 'field', 75, 'dataset'),
('下单', '订单数量', 'field', 80, 'dataset'),
('下过单', '订单数量', 'field', 70, 'dataset'),
('买过', '支付金额', 'field', 65, 'dataset'),
('首次购买', '订单数量', 'field', 60, 'dataset'),
('首次下单', '订单数量', 'field', 55, 'dataset'),
('注册时间', '用户数量', 'field', 65, 'dataset'),
('注册日期', '用户数量', 'field', 60, 'dataset'),
('活跃度', '用户数量', 'field', 55, 'dataset'),
('等级', '用户等级', 'field', 70, 'dataset'),
('VIP', '用户等级', 'field', 65, 'dataset'),
('用户等级', '用户等级', 'field', 60, 'dataset'),
('封禁', '用户状态', 'value', 55, 'dataset'),
('已封禁', '用户状态', 'value', 50, 'dataset'),
('未激活', '用户状态', 'value', 55, 'dataset'),
('已激活', '用户状态', 'value', 50, 'dataset'),
('邮箱', '用户数量', 'field', 60, 'dataset'),
('邮箱绑定', '用户数量', 'field', 55, 'dataset'),
('绑定邮箱', '用户数量', 'field', 50, 'dataset'),
('邮箱地址', '用户数量', 'field', 45, 'dataset'),
('qq.com', '用户数量', 'field', 50, 'dataset'),
('默认地址', '用户数量', 'field', 55, 'dataset'),
('默认收货地址', '用户数量', 'field', 50, 'dataset'),
('收货地址', '用户数量', 'field', 60, 'dataset'),
('多个地址', '用户数量', 'field', 50, 'dataset'),
('几个地址', '用户数量', 'field', 45, 'dataset'),
('姓名', '用户数量', 'field', 50, 'dataset'),
('张三', '用户数量', 'field', 40, 'dataset'),
('姓张', '用户数量', 'field', 45, 'dataset'),
('花名', '用户数量', 'field', 40, 'dataset'),
('余额', '账户余额', 'field', 65, 'dataset'),
('可用余额', '账户余额', 'field', 60, 'dataset'),
('积分', '用户数量', 'field', 60, 'dataset'),
('复购', '用户数量', 'field', 55, 'dataset'),
('复购率', '用户数量', 'field', 60, 'dataset'),
('回头客', '用户数量', 'field', 55, 'dataset'),
('回头率', '用户数量', 'field', 50, 'dataset'),

-- ========== 地区相关 ==========
('省份', '用户数量', 'field', 65, 'dataset'),
('城市', '用户数量', 'field', 70, 'dataset'),
('区县', '用户数量', 'field', 60, 'dataset'),
('地区', '用户数量', 'field', 65, 'dataset'),
('省份分布', '用户数量', 'field', 55, 'dataset'),
('城市分布', '用户数量', 'field', 50, 'dataset'),
('华东', '用户数量', 'field', 45, 'dataset'),
('华南', '用户数量', 'field', 45, 'dataset'),
('华北', '用户数量', 'field', 45, 'dataset'),
('上海', '用户数量', 'field', 50, 'dataset'),
('北京', '用户数量', 'field', 50, 'dataset'),

-- ========== 时间相关 ==========
('本月', '下单时间', 'field', 70, 'dataset'),
('本月内', '下单时间', 'field', 65, 'dataset'),
('本月订单', '下单时间', 'field', 60, 'dataset'),
('今年', '下单时间', 'field', 70, 'dataset'),
('去年', '下单时间', 'field', 65, 'dataset'),
('上月', '下单时间', 'field', 60, 'dataset'),
('上月订单', '下单时间', 'field', 55, 'dataset'),
('本月', '下单时间', 'field', 60, 'dataset'),
('按月', '下单时间', 'field', 65, 'dataset'),
('每月', '下单时间', 'field', 70, 'dataset'),
('月份', '下单时间', 'field', 75, 'dataset'),
('各月', '下单时间', 'field', 70, 'dataset'),
('每月订单', '下单时间', 'field', 65, 'dataset'),
('月环比', '下单时间', 'field', 55, 'dataset'),
('环比增长', '下单时间', 'field', 50, 'dataset'),
('增长率', '下单时间', 'field', 55, 'dataset'),
('最近7天', '下单时间', 'field', 60, 'dataset'),
('最近一个月', '下单时间', 'field', 55, 'dataset'),
('7天内', '下单时间', 'field', 50, 'dataset'),
('累计', '下单时间', 'field', 60, 'dataset'),
('累计GMV', '活动实际GMV', 'field', 55, 'dataset'),
('累计销售额', '活动实际GMV', 'field', 50, 'dataset'),
('2024年', '下单时间', 'field', 60, 'dataset'),
('2024年1月', '下单时间', 'field', 55, 'dataset'),
('2024年6月', '下单时间', 'field', 50, 'dataset'),

-- ========== 统计相关 ==========
('排名', '订单数量', 'field', 75, 'dataset'),
('前10', '订单数量', 'field', 70, 'dataset'),
('前5', '订单数量', 'field', 65, 'dataset'),
('前3', '订单数量', 'field', 60, 'dataset'),
('Top10', '订单数量', 'field', 65, 'dataset'),
('Top5', '订单数量', 'field', 60, 'dataset'),
('排行榜', '订单数量', 'field', 70, 'dataset'),
('排名榜', '订单数量', 'field', 65, 'dataset'),
('第1名', '订单数量', 'field', 55, 'dataset'),
('并列', '订单数量', 'field', 50, 'dataset'),
('并列排名', '订单数量', 'field', 45, 'dataset'),
('占比', '订单数量', 'field', 70, 'dataset'),
('百分比', '订单数量', 'field', 60, 'dataset'),
('比例', '订单数量', 'field', 65, 'dataset'),
('平均', '客单价', 'field', 75, 'dataset'),
('平均值', '客单价', 'field', 70, 'dataset'),
('人均', '客单价', 'field', 65, 'dataset'),
('总计', '订单总金额', 'field', 70, 'dataset'),
('合计', '订单总金额', 'field', 75, 'dataset'),
('总额', '订单总金额', 'field', 80, 'dataset'),
('总和', '订单总金额', 'field', 70, 'dataset'),
('总笔数', '订单数量', 'field', 75, 'dataset'),
('总共', '订单数量', 'field', 70, 'dataset'),
('一共有', '订单数量', 'field', 65, 'dataset'),
('有多少', '订单数量', 'field', 70, 'dataset'),
('多少笔', '订单数量', 'field', 65, 'dataset'),
('多少单', '订单数量', 'field', 60, 'dataset'),
('多少个', '订单数量', 'field', 55, 'dataset'),
('变化趋势', '订单数量', 'field', 60, 'dataset'),
('趋势', '订单数量', 'field', 55, 'dataset'),
('增长', '订单数量', 'field', 60, 'dataset'),
('下降', '订单数量', 'field', 55, 'dataset'),
('转化率', '订单数量', 'field', 70, 'dataset'),
('转化', '订单数量', 'field', 65, 'dataset'),
('高于', '平均评分', 'field', 60, 'dataset'),
('超过', '平均评分', 'field', 65, 'dataset'),
('低于', '平均评分', 'field', 55, 'dataset'),
('高于平均', '平均评分', 'field', 60, 'dataset'),
('超过平均', '平均评分', 'field', 55, 'dataset'),
('比平均高', '平均评分', 'field', 50, 'dataset'),
('退款率', '退款商品数量', 'field', 65, 'dataset'),
('退款比', '退款商品数量', 'field', 55, 'dataset'),
('用户流失', '用户数量', 'field', 50, 'dataset'),
('新用户', '用户数量', 'field', 60, 'dataset'),
('新增', '用户数量', 'field', 65, 'dataset'),
('新增用户', '用户数量', 'field', 60, 'dataset'),
('老用户', '用户数量', 'field', 55, 'dataset'),

-- ========== 分类相关 ==========
('分类', '商品状态', 'field', 75, 'dataset'),
('类目', '商品状态', 'field', 70, 'dataset'),
('品类', '商品状态', 'field', 65, 'dataset'),
('一级分类', '商品状态', 'field', 70, 'dataset'),
('一级类目', '商品状态', 'field', 65, 'dataset'),
('一级品类', '商品状态', 'field', 60, 'dataset'),
('二级分类', '商品状态', 'field', 65, 'dataset'),
('子分类', '商品状态', 'field', 60, 'dataset'),
('下级分类', '商品状态', 'field', 55, 'dataset'),
('包含', '商品状态', 'field', 60, 'dataset'),
('下属', '商品状态', 'field', 55, 'dataset'),
('下属分类', '商品状态', 'field', 50, 'dataset'),
('上级分类', '商品状态', 'field', 55, 'dataset'),
('顶级', '商品状态', 'field', 50, 'dataset'),
('顶级类目', '商品状态', 'field', 45, 'dataset'),
('上级为空', '商品状态', 'field', 40, 'dataset'),
('手机通讯', '商品状态', 'field', 45, 'dataset'),
('手机', '商品状态', 'field', 50, 'dataset'),
('数码', '商品状态', 'field', 45, 'dataset'),
('移动设备', '商品状态', 'field', 40, 'dataset'),
('有多少个分类', '商品状态', 'field', 45, 'dataset'),
('有几个分类', '商品状态', 'field', 40, 'dataset'),

-- ========== SQL/技术相关 ==========
('行转列', '订单数量', 'field', 55, 'dataset'),
('列转行', '订单数量', 'field', 50, 'dataset'),
('子查询', '订单数量', 'field', 45, 'dataset'),
('嵌套查询', '订单数量', 'field', 40, 'dataset'),
('窗口函数', '订单数量', 'field', 45, 'dataset'),
('CTE', '订单数量', 'field', 40, 'dataset'),
('WITH', '订单数量', 'field', 35, 'dataset'),
('JOIN', '订单数量', 'field', 50, 'dataset'),
('关联', '订单数量', 'field', 55, 'dataset'),
('联表', '订单数量', 'field', 50, 'dataset'),
('表连接', '订单数量', 'field', 45, 'dataset'),
('GROUP BY', '订单数量', 'field', 50, 'dataset'),
('分组', '订单数量', 'field', 60, 'dataset'),
('排序', '订单数量', 'field', 65, 'dataset'),
('ORDER BY', '订单数量', 'field', 55, 'dataset'),
('LIMIT', '订单数量', 'field', 50, 'dataset'),
('DISTINCT', '订单数量', 'field', 45, 'dataset'),
('去重', '订单数量', 'field', 50, 'dataset'),
('HAVING', '订单数量', 'field', 40, 'dataset'),
('LIKE', '订单数量', 'field', 45, 'dataset'),
('模糊搜索', '订单数量', 'field', 40, 'dataset'),
('包含关键字', '订单数量', 'field', 45, 'dataset'),
('以XX开头', '订单数量', 'field', 40, 'dataset'),
('前缀', '订单数量', 'field', 35, 'dataset'),
('后缀', '订单数量', 'field', 35, 'dataset'),
('NULL', '订单数量', 'field', 40, 'dataset'),
('不为空', '订单数量', 'field', 45, 'dataset'),
('空值', '订单数量', 'field', 40, 'dataset'),
('非空', '订单数量', 'field', 35, 'dataset'),

-- ========== 高级分析相关 ==========
('年龄段', '用户数量', 'field', 55, 'dataset'),
('18-25', '用户数量', 'field', 45, 'dataset'),
('26-35', '用户数量', 'field', 45, 'dataset'),
('36-45', '用户数量', 'field', 45, 'dataset'),
('45+', '用户数量', 'field', 40, 'dataset'),
('年龄段分布', '用户数量', 'field', 50, 'dataset'),
('消费能力', '支付金额', 'field', 55, 'dataset'),
('用户画像', '用户数量', 'field', 50, 'dataset'),
('购买力', '支付金额', 'field', 50, 'dataset'),
('购买频次', '订单数量', 'field', 55, 'dataset'),
('购买间隔', '订单数量', 'field', 50, 'dataset'),
('领券间隔', '优惠券领取数量', 'field', 45, 'dataset'),
('连续', '订单数量', 'field', 50, 'dataset'),
('连续3个月', '订单数量', 'field', 45, 'dataset'),
('RFM', '支付金额', 'field', 40, 'dataset'),
('同商品', '商品购买数量', 'field', 50, 'dataset'),
('相同商品', '商品购买数量', 'field', 55, 'dataset'),
('其他客户', '用户数量', 'field', 50, 'dataset'),
('复购分析', '订单数量', 'field', 50, 'dataset'),
('关联购买', '订单数量', 'field', 45, 'dataset'),
('连带率', '订单数量', 'field', 40, 'dataset'),
('Basket', '订单数量', 'field', 35, 'dataset'),
('商品关联', '商品购买数量', 'field', 45, 'dataset')
ON DUPLICATE KEY UPDATE `frequency` = VALUES(`frequency`), `source` = VALUES(`source`);


-- ============================================================
-- 步骤3：补充表元信息表
-- ============================================================

INSERT INTO `table_metadata` (`table_name`, `table_cn_name`, `description`, `domain`, `core_scenarios`) VALUES
('store_ratings', '店铺评分表', '店铺DSR动态评分、是否有图评价、评价内容', '店铺域', '["店铺评分分析", "好评率统计", "有图/无图评价对比", "DSR监控"]'),
('user_coupons', '用户优惠券表', '用户领券、用券、过期记录', '营销域', '["优惠券核销分析", "领券分析", "用券率统计", "过期券分析"]'),
('product_specs', '商品规格表', 'SKU规格信息、颜色尺码、库存价格', '商品域', '["SKU分析", "规格销量", "颜色分布", "尺码统计"]')
ON DUPLICATE KEY UPDATE `description` = VALUES(`description`), `core_scenarios` = VALUES(`core_scenarios`);


-- ============================================================
-- 步骤4：补充表关联关系表
-- ============================================================

INSERT INTO `table_relations` (`main_table`, `related_table`, `join_condition`, `join_type`, `description`) VALUES
-- 评分相关关联
('stores', 'store_ratings', 'stores.store_id = store_ratings.store_id', 'LEFT', '店铺-评分 一对多'),
('users', 'store_ratings', 'users.user_id = store_ratings.user_id', 'LEFT', '用户-评分 一对多'),
('orders', 'store_ratings', 'orders.order_id = store_ratings.order_id', 'LEFT', '订单-评分 一对一'),
('products', 'order_items', 'products.product_id = order_items.product_id', 'LEFT', '商品-订单明细 一对多'),
-- 优惠券相关关联
('coupons', 'user_coupons', 'coupons.coupon_id = user_coupons.coupon_id', 'LEFT', '优惠券-用户领取 一对多'),
('users', 'user_coupons', 'users.user_id = user_coupons.user_id', 'LEFT', '用户-领券记录 一对多'),
('orders', 'user_coupons', 'orders.order_id = user_coupons.order_id', 'LEFT', '订单-用券记录 一对一(可能NULL)'),
-- 支付相关关联
('payments', 'orders', 'payments.order_id = orders.order_id', 'LEFT', '支付-订单 一对一'),
('payments', 'users', 'payments.user_id = users.user_id', 'LEFT', '支付-用户 一对多'),
-- 物流相关关联
('shipments', 'orders', 'shipments.order_id = orders.order_id', 'LEFT', '物流-订单 一对一'),
('shipments', 'stores', 'shipments.store_id = stores.store_id', 'LEFT', '物流-店铺 一对多'),
('shipment_tracks', 'shipments', 'shipment_tracks.shipment_id = shipments.shipment_id', 'LEFT', '物流轨迹-物流单 一对多'),
-- 规格关联
('products', 'product_specs', 'products.product_id = product_specs.product_id', 'LEFT', '商品-SKU 一对多'),
-- 促销与订单关联
('campaigns', 'orders', 'orders.store_id IS NOT NULL AND campaigns.store_id = orders.store_id', 'LEFT', '活动-店铺订单 条件关联')
ON DUPLICATE KEY UPDATE `join_condition` = VALUES(`join_condition`), `description` = VALUES(`description`);


-- ============================================================
-- 步骤5：更新序列值
-- ============================================================
-- 如果需要确保序列连续

SELECT '语义层数据更新完成!' AS status;
SELECT CONCAT('标准指标维度: ', COUNT(*), ' 条') AS metrics_count FROM standard_metrics_dimensions;
SELECT CONCAT('口语别名: ', COUNT(*), ' 条') AS aliases_count FROM spoken_aliases;
SELECT CONCAT('表元信息: ', COUNT(*), ' 条') AS tables_count FROM table_metadata;
SELECT CONCAT('表关联: ', COUNT(*), ' 条') AS relations_count FROM table_relations;
